appid := env('APPID')
install-dir := env('INSTALL_DIR')
desktop-src := appid + '.desktop'
desktop-dst := install-dir / 'applications' / desktop-src
metainfo-src := appid + '.metainfo.xml'
metainfo-dst := install-dir / 'metainfo' / metainfo-src

install:
    install -Dm0644 {{ desktop-src }} {{ desktop-dst }}
    install -Dm0644 {{ metainfo-src }} {{ metainfo-dst }}

uninstall:
    rm -r {{ desktop-dst }} {{ metainfo-dst }}
